### ISSUE TITLE
Unable to parse latest factorio api

### ISSUE THREAD

**Issue by knoxfighter** [knoxfighter/intellij-factorio-autocompletion#11]
Since factorio 1.1.49 the new api format is finished and used. The current parser is not able to parse that new format.

**Comment by oorzkws** [comment]
I'm assuming that's what's resulting in the following? Otherwise I'll open a separate issue
```
java.lang.NullPointerException
	at moe.knox.factorio.parser.FactorioApiParser.downloadAndParseAPI(FactorioApiParser.java:693)
	at moe.knox.factorio.parser.FactorioApiParser.assureDir(FactorioApiParser.java:652)
	at moe.knox.factorio.parser.FactorioApiParser.run(FactorioApiParser.java:126)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by knoxfighter** [comment]
yes, that is the error for that :)

**Comment by MeblIkea** [comment]
And so is there a way to fix it please? (Or can someone update the plugin into Jetbrains ? :/)
