### ISSUE TITLE
Stuck on Download Factorio Lualib

### ISSUE THREAD

**Issue by kalbert312** [knoxfighter/intellij-factorio-autocompletion#3]
Hi. I just installed this plugin but it seems like it never finishes this step:
![Screen Shot 2020-02-10 at 12 41 22 PM](https://user-images.githubusercontent.com/5498623/74174837-aa5ba600-4c02-11ea-9375-f7cd95b4bc55.png)

**Comment by kid2407** [comment]
I can reproduce this, looking at the logs shows that it repeatedly prints the following stacktrace to the log:
```
java.lang.Throwable: Factorio API changed
	at moe.knox.factorio.library.FactorioLibraryProvider.lambda$reload$0(FactorioLibraryProvider.java:99)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:98)
	at moe.knox.factorio.library.FactorioLibraryProvider.reload(FactorioLibraryProvider.java:93)
	at moe.knox.factorio.parser.FactorioPrototypeParser.removeCurrentPrototypes(FactorioPrototypeParser.java:105)
	at moe.knox.factorio.FactorioStartupActivity.runActivity(FactorioStartupActivity.java:22)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:216)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$1(StartupManagerImpl.java:177)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:396)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:388)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:68)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
This looks like and endelss loop to me.
I am using the latest Intellij Version, currently 2019.3.2, build 193.6015.39

**Comment by kalbert312** [comment]
I don't know IntelliJ plugin development but this might be the cause: https://github.com/knoxfighter/intellij-factorio-autocompletion/blob/master/src/main/java/moe/knox/factorio/parser/FactorioLualibParser.java#L217.

Should it be `/core/lualib/`? https://github.com/wube/factorio-data/tree/master/core

**Comment by kalbert312** [comment]
https://github.com/knoxfighter/intellij-factorio-autocompletion/pull/4

**Comment by knoxfighter** [comment]
I managed to find this error too and i dont have found the error yet.
And also the Stacktrace you posted @kid2407 is normal behaviour and is just there, to assure, that the files are reindexed.

**Comment by knoxfighter** [comment]
ok, i found the error and also fixed a few more, so this should not happen again :crossed_fingers:

**Comment by knoxfighter** [comment]
Update got accepted by jetbrains and can be downloaded from the pugins repository.

**Comment by kalbert312** [comment]
Thank you. Appears to be working now. Also glad this exists. Super useful to someone with lots of IntelliJ use but almost no working knowledge of Lua or Factorio modding 👍
